# Generated by Django 5.0.3 on 2024-04-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_tag_order_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Tag',
        ),
        migrations.AddField(
            model_name='product',
            name='Tag',
            field=models.ManyToManyField(to='Accounts.tag'),
        ),
    ]
